CREATE TABLE TRANSACTION (
    ID BIGINT NOT NULL,
    CATEGORY VARCHAR(256) NOT NULL,
    AMOUNT DOUBLE NOT NULL,
    DESCRIPTION VARCHAR(256) NOT NULL,
    DATE DATE,
	PRIMARY KEY (ID)
);
CREATE TABLE CATEGORY (
    ID BIGINT NOT NULL,
    NAME VARCHAR(256) NOT NULL
);
